INSERT INTO PASSO_A_PASSO (ID, NUM1, OPERACAO, NUM2, RESULTADO, DATA_HORA)
VALUES (idcalculo.nextval, ?, ?, ?, ?, TRUNC(SYSDATE, 'MI'));

INSERT INTO UMA_LINHA (ID, CALCULO, RESULTADO, DATA_HORA)
VALUES (idcalculo.nextval, ?, ?, TRUNC(SYSDATE, 'MI'));


SELECT
       A.NUM1 || ' ' || B.DS_OPERACAO || ' ' || A.NUM2 CALCULO,
       A.RESULTADO RESULTADO,
       TO_CHAR(A.DATA_HORA, 'DD/MM/YYYY HH24:MI:SS') DATA_HORA_REGISTRO
FROM PASSO_A_PASSO A LEFT JOIN OPERACOES B ON A.OPERACAO = B.ID_OPERACAO
UNION ALL
SELECT
       C.CALCULO CALCULO,
       C.RESULTADO RESULTADO,
       TO_CHAR(C.DATA_HORA, 'DD/MM/YYYY HH24:MI:SS') DATA_HORA_REGISTRO
FROM UMA_LINHA C
ORDER BY 3;


SELECT * FROM OPERACOES;
SELECT * FROM PASSO_A_PASSO;
SELECT * FROM UMA_LINHA;

DELETE FROM PASSO_A_PASSO WHERE DATA_HORA < (SYSDATE - INTERVAL '12' HOUR);
DELETE FROM UMA_LINHA WHERE DATA_HORA < (SYSDATE - INTERVAL '12' HOUR);

UPDATE PASSO_A_PASSO
SET DATA_HORA = '03/05/2023 18:27:45'
WHERE id = ?;

ALTER SEQUENCE IDCALCULO RESTART;

SELECT IDCALCULO.NEXTVAL FROM DUAL;

COMMIT;
